apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-v1
  namespace: temp
spec:
  replicas: 2 
  template:
    metadata:
      labels:
        app: springboot
        version: v1
    spec:
      containers:
      - name: springboot
        image: helloworld:1.0.0
        ports:
        - containerPort: 8080
  selector:
    matchLabels:
      app: springboot
      version: v1
  